name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core
          user: marcreichel
          config_timezone: Europe/Berlin
          committer_message: "chore: update metrics"
          
          # Display
          template: classic
          base: header
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year                        # Display full year instead of half year
          
          plugin_languages: yes
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: detailed # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          
          plugin_introduction: yes
          
          plugin_habits: yes
          plugin_habits_from: 1000       # Use 200 events to compute habits
          plugin_habits_days: 30        # Keep only events from last 14 days
          plugin_habits_facts: no       # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          
          plugin_people: yes
          plugin_people_types: followers     # Display followers and "thanks" sections
          plugin_people_shuffle: yes         # Shuffle for varied output
          
          plugin_rss: yes
          plugin_rss_source: https://marcreichel.dev/blog.atom  # RSS feed
          plugin_rss_limit: 3                                  # Limit to 6 items
          
