name: Profile
on:
  # Schedule updates (each day)
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Download Light SVG
        run: curl https://marcreichel.dev/github-profile -o profile-dark.svg
      - name: Download Dark SVG
        run: curl https://marcreichel.dev/github-profile?dark -o profile-light.svg
      - uses: stefanzweifel/git-auto-commit-action@v4
